### ISSUE TITLE
GAM and partial deviances 

### ISSUE THREAD

**Issue by mhepner90** [mhepner90/RVC#12]
"RVC_diveristy_analysis.Rmd" chunk 20: Gam and partial deviances 

Hi @bbest --- Can you please take a look at chunk 20 and see what I am missing.... 

Need to run chunk 17: mapping libraries first to define "cl" 

I am trying to run my 7 indices through my GAM and compute partial deviances for each variable (time, space, environment, management), but I keep receiving the following error: 

Error in checkForRemoteErrors(val) : 
  8 nodes produced errors; first error: 'data' argument is of the wrong type

Megan

**Comment by bbest** [comment]
Hi @mhepner90,

When I run this line from inside the loop of chunk 19 "GAM and Partial deviances":

```r
fullmod = gam(formula(paste(j,"~YEAR+STRAT+PROT+s(LONG_DEGREES,LAT_DEGREES,by=YEAR, bs='ts')+s(DEPTH, by='ts')")), family=poisson, data=data)
```
I get the following error:

```
Error in terms.formula(formula, data = data) : 
  invalid model formula in ExtractVars
```

You have a couple tiny typos with this formula:

1. `LONG_DEGREES` does not exist in `names(data)`; should be `LON_DEGREES`
1. In `s(DEPTH, by='ts')`, `ts` is also not in `names(data)`, but think you wanted to keep the tensor smoother (ts) and instead of defining that term "by" another, use ts as your basis function (`bs`); should be `s(DEPTH, bs='ts')`

This works:

```r
fullmod = gam(formula(paste(j,"~YEAR+STRAT+PROT+s(LON_DEGREES,LAT_DEGREES,by=YEAR, bs='ts')+s(DEPTH, bs='ts')")), family=poisson, data=data)
```
